### ISSUE TITLE
Wake me up when the code is released

### ISSUE THREAD

**Issue by nitinmukesh** [NVlabs/Sana#1]

**Comment by newgenai79** [comment]
Okies

**Comment by xieenze** [comment]
Hi all, we are waiting for internal approval. Please be patient.

**Comment by XyW-Max** [comment]
Good things come to those who wait.

**Comment by ptits** [comment]
wake me too

**Comment by iamwavecut** [comment]
wake me up when the weights online

**Comment by DewiarQR** [comment]
I'm in line too

**Comment by Njasa2k** [comment]
I'm interested.

**Comment by zyzzyh** [comment]
wake me up too

**Comment by xieenze** [comment]
Hi all, the code is released. 🙂

**Comment by ptits** [comment]
When do you plan to release weights?

https://huggingface.co/Efficient-Large-Model/Sana_1600M_1024px/checkpoints/Sana_1600M_1024px.pth is broken link
