### ISSUE TITLE
VAE Training details

### ISSUE THREAD

**Issue by lavinal712** [NVlabs/Sana#10]
Your deep compression autoencoder shows that vae with high downsample factor like 32 also performs well id diffusion models. What is your training methods? Do you adopt [latent-diffusion](https://github.com/CompVis/latent-diffusion/tree/main) code as the base code for the training?

Thanks for your works!

**Comment by markywg** [comment]
I suppose you can find it under https://github.com/mit-han-lab/efficientvit.

**Comment by lavinal712** [comment]
I get it. Thanks.
