### ISSUE TITLE
2k model generating very bad output :(

### ISSUE THREAD

**Issue by nitinmukesh** [NVlabs/Sana#106]
![sana](https://github.com/user-attachments/assets/41f7c66b-de48-477c-9438-ef4764e94a40)

![a_cyberpun_2024-12-20_21-23-10](https://github.com/user-attachments/assets/5981cfae-025c-4868-8e9b-a8771671f9f9)

"Efficient-Large-Model/Sana_1600M_2Kpx_BF16_diffusers",
    variant="bf16",
    torch_dtype=torch.bfloat16,
prompt = 'a cyberpunk cat with a neon sign that says "Sana"'
height=2048,
    width=2048,
    guidance_scale=5.0,
    num_inference_steps=20,

**Comment by nitinmukesh** [comment]
With CFG to 2.0

![sana](https://github.com/user-attachments/assets/b9ef5012-4dc0-449c-afa3-8d526293680f)

**Comment by lawrence-cj** [comment]
diffusers bug is fixed.
