### ISSUE TITLE
The model is pretty good, but... when will it be open source? 

### ISSUE THREAD

**Issue by win10ogod** [NVlabs/Sana#11]
The model is pretty good, but... when will it be open source?

**Comment by xieenze** [comment]
Hi, the code is released. 🙂

**Comment by win10ogod** [comment]
> Hi, the code is released. 🙂

When will the weights be released to the public?

**Comment by Lime-Cakes** [comment]
> > Hi, the code is released. 🙂
> 
> When will the weights be released to the public?

Just released
