### ISSUE TITLE
Requesting to release 16:9 and 9:16 models

### ISSUE THREAD

**Issue by nitinmukesh** [NVlabs/Sana#112]
As we all know the generated images are awesome. Many thanks to you and your team.

Please release the 2K quality models (diffusers) in aspect ratio as mentioned in title.

e.g.
1024 x 576 and 576 x 1024
or
1920 x 1080 and 1080 x 1920

![A_mythical_2024-12-23_21-43-36](https://github.com/user-attachments/assets/c51dba57-1025-4782-ae55-645fc3965f53)

![A_grand_li_2024-12-23_21-45-54](https://github.com/user-attachments/assets/bb0a9629-0020-47f6-b87e-a99df0f96d8e)

**Comment by lawrence-cj** [comment]
We train the model with multi-resolution, this aspect ratio should be handled naturally.

**Comment by nitinmukesh** [comment]
Oh! I didn't even tried. In ReadMe it's mentioned as 512x512, 1024x1024 and 2K so I thought the training dataset included only squared images.

My bad. Will try.
