### ISSUE TITLE
Resolution error

### ISSUE THREAD

**Issue by Minimidget007-WE** [NVlabs/Sana#114]
RuntimeError: Error(s) in loading state_dict for SanaMS:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 4096, 2240]) from checkpoint, the shape in current model is torch.Size([1, 1024, 2240]).
        
        
I am beginner to this type of stuff using the sample workflow but have no clue how to fix this issue have changed almost everything downloaded like 50gb of vae thought that maybe that was the problem but to no solution I've turned to ask for help in this error

**Comment by lawrence-cj** [comment]
Are you using our ComfyUI nodes to load the 2K checkpoint?

**Comment by Minimidget007-WE** [comment]
![Screenshot 2024-12-25 102811](https://github.com/user-attachments/assets/325791e5-35ca-4706-a4bf-c3cbee4ccee1)
This is my whole setup it should be using the right ones but i might be wrong

**Comment by nitinmukesh** [comment]
@Minimidget007-WE 

If you want to try outside Comfy, try this
https://github.com/newgenai79/newgenai

**Comment by Minimidget007-WE** [comment]
@nitinmukesh 
Yeah i used the gradio version and it worked fine, but i want to learn ComfyUI for its extra capabilities like upscalers and controllnets that will be added later on

**Comment by Minimidget007-WE** [comment]
Decided to use the 1024px one since i thought maybe my pc is bad got this instead
![image](https://github.com/user-attachments/assets/425212df-18c5-4dce-b956-8da63430f178)
used this model before and worked and now it doesnt kinda odd ngl but hey im new to this thing and reset my pc so some stuff could be missing might have to look into things, maybe need to installa conda and pytorch but then it shoulnt be able to run if those were the issue

**Comment by Minimidget007-WE** [comment]
@lawrence-cj Do i need to install the diffuser model for the 2k to work, if so can you tell me which ones to install i can see 3 models in the transformer model on hugginface

**Comment by lawrence-cj** [comment]
For simplicity, just use this one: https://huggingface.co/Efficient-Large-Model/Sana_1600M_2Kpx_BF16_diffusers/blob/main/transformer/diffusion_pytorch_model.bf16.safetensors

**Comment by Minimidget007-WE** [comment]
ExtraVAELoader
No module named 'diffusers'
3 install still getting this issue no clue kinda thinking about giving up on this tho but im trying

**Comment by Minimidget007-WE** [comment]
@lawrence-cj 
Sorry for another ping but any solution you know of to this?? 
![image](https://github.com/user-attachments/assets/57508831-fc81-4af7-b9aa-6bbf1c78e11e)

**Comment by shaun-ba** [comment]
> For simplicity, just use this one: https://huggingface.co/Efficient-Large-Model/Sana_1600M_2Kpx_BF16_diffusers/blob/main/transformer/diffusion_pytorch_model.bf16.safetensors

Hi @lawrence-cj , where should this file be placed? I also tried with the PTH 6GB version and got the same error as OP. I am also using ComfyUI

**Comment by lawrence-cj** [comment]
Hi, @Minimidget007-WE . You solved the problem?

**Comment by lawrence-cj** [comment]
What is the error specifically? @shaun-ba

**Comment by shaun-ba** [comment]
@lawrence-cj  Exactly the same as the OP. I tried all available settings in the ComfyUI nodes and even tried edited the nodes code myself (not a coder) to add another model with higher "hidden_size" in the event that was the issue. Got various other errors and fixed them but then gave up

```
RuntimeError: Error(s) in loading state_dict for SanaMS:
size mismatch for pos_embed: copying a param with shape torch.Size([1, 4096, 2240]) from checkpoint, the shape in current model is torch.Size([1, 1024, 2240]).
```
