### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by VeteranXT** [NVlabs/Sana#117]
When i downloaded ComfyUI extension it downloaded all things all models.
When i did press Enter 
it gave me following error [Errno 2] No such file or directory: 'E:\\Storage\\Apps\\AI_Geneartor\\ComfyUI\\models\\sana\\models--sana--sana-600m-512px/checkpoints/Sana_600M_512px.pth'

This is workflow. 
![image](https://github.com/user-attachments/assets/38f63ecd-e2b7-4767-a1e9-ffe13365e813)
Also There is **Sana_600M_512px_MultiLing.pth** on that location.

**Comment by Minimidget007-WE** [comment]
Click on you checkpoint loader the spot where you choose which checkpoint one then you can choose Sana_600M_512px_MultiLing.pth since it seems like you are trying to use another one that is not in your file, the right one should probably be the bottom one

**Comment by VeteranXT** [comment]
![image](https://github.com/user-attachments/assets/6acd5f6c-1f1c-4e90-8cc6-b09c3c114127)
this is what i selected.

![image](https://github.com/user-attachments/assets/54c9dcc5-b2cc-4059-959e-c4e5fc4ccf8c)

No matter that model i select i get same error.

**Comment by VeteranXT** [comment]
> Click on you checkpoint loader the spot where you choose which checkpoint one then you can choose Sana_600M_512px_MultiLing.pth since it seems like you are trying to use another one that is not in your file, the right one should probably be the bottom one

There is no Sana_600M_512px_MultiLing.pth

**Comment by VeteranXT** [comment]
> Click on you checkpoint loader the spot where you choose which checkpoint one then you can choose Sana_600M_512px_MultiLing.pth since it seems like you are trying to use another one that is not in your file, the right one should probably be the bottom one

I do not have Sana_600M_512px_MultiLing.pth to select. Where is it?

**Comment by Minimidget007-WE** [comment]
@VeteranXT It seem like you downloaded it in the place it should not be installed in the sans folder but the checkpoint folder in the models directory

**Comment by VeteranXT** [comment]
> @VeteranXT It seem like you downloaded it in the sana folder but it should be installed in the checkpoint folder in the models directory

I didn't download. Extension did. It  said it downloads everything once you press generate. 
What i did is install custom extension suggested, drag workflow, add prompt press generate and this is the issue.

**Comment by VeteranXT** [comment]
> > @VeteranXT It seem like you downloaded it in the sana folder but it should be installed in the checkpoint folder in the models directory
> 
> I didn't download. Extension did. It said it downloads everything once you press generate. What i did is install custom extension suggested, drag workflow, add prompt press generate and this is the issue.

this Custom https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels or https://github.com/city96/ComfyUI_ExtraModels

**Comment by Minimidget007-WE** [comment]
Yeah I saw a video saying that it does for some reason install in the wrong place just put the models you want to downalod from the checpiont folder in the model folder it should most probably work then

**Comment by VeteranXT** [comment]
> Yeah I saw a video saying that it does for some reason install in the wrong place just put the models you want to download from the checkpoint folder in the model folder it should most probably work then but do the second link the first one extra models is broken

Now i downloaded other one. I placed checkpoint into models/checkpoint, now i have this error. `!!! Exception during processing !!! Error(s) in loading state_dict for SanaMS:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 256, 1152]) from checkpoint, the shape in current model is torch.Size([1, 1024, 1152]).
Traceback (most recent call last):
  File "E:\Storage\Apps\AI_Geneartor\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Storage\Apps\AI_Geneartor\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\Storage\Apps\AI_Geneartor\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Storage\Apps\AI_Geneartor\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\Storage\Apps\AI_Geneartor\ComfyUI\custom_nodes\ComfyUI_ExtraModels\Sana\nodes.py", line 86, in load_checkpoint
    model = load_sana(
  File "E:\Storage\Apps\AI_Geneartor\ComfyUI\custom_nodes\ComfyUI_ExtraModels\Sana\loader.py", line 88, in load_sana
    m, u = model.diffusion_model.load_state_dict(state_dict, strict=False)
  File "E:\Storage\Apps\AI_Geneartor\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SanaMS:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 256, 1152]) from checkpoint, the shape in current model is torch.Size([1, 1024, 1152]).`

**Comment by VeteranXT** [comment]
Switching to https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels solved initial issue.
