### ISSUE TITLE
ExtraVAELoader No module named 'diffusers'

### ISSUE THREAD

**Issue by Minimidget007-WE** [NVlabs/Sana#118]
This is my workflow its from the sample workflow
![image](https://github.com/user-attachments/assets/307b2449-29d4-4202-bc0f-fbe6015dc806)
I've tried many thing to resolve this issue and have yet to be successful
been reinstalling it 5 times newest one I've tried with venv and still the same issue, I've got one to work if i use the original city96 custom node to work but then it gives me grey or black images and it seems they got a fix for it but this is what mi getting now

**Comment by shaun-ba** [comment]
Install diffusers package, it's literally in the README for this repo.

**Comment by Minimidget007-WE** [comment]
@shaun-ba  No problem bro they just need to add where its suppose to be installed since i installed it almost everywhere and had no solution, it had to go in  the python embed no since most people are beginners at this you think that it be there tbh or at the readme it would say where to install it
