### ISSUE TITLE
there are no weights on hf

### ISSUE THREAD

**Issue by ptits** [NVlabs/Sana#15]
When do you plan to release weights?

https://huggingface.co/Efficient-Large-Model/Sana_1600M_1024px/checkpoints/Sana_1600M_1024px.pth is broken link

**Comment by vaskers5** [comment]
+++

**Comment by wuutiing** [comment]
withdrawed or not released yet?

**Comment by nitinmukesh** [comment]
Not released yet

**Comment by lawrence-cj** [comment]
Released.
