### ISSUE TITLE
How to use configs\sana_config\512ms\Sana_600M_img512.yaml

### ISSUE THREAD

**Issue by nitinmukesh** [NVlabs/Sana#17]
The following goes out of memory on 15.9 GB
configs\sana_config\512ms\Sana_1600M_img512.yaml --model_path Efficient-Large-Model\Sana_1600M_512px\checkpoints\Sana_1600M_512px.pth

**Comment by nitinmukesh** [comment]
Hardware requirement
9GB VRAM is required for 0.6B model and 12GB VRAM for 1.6B model.

**Comment by lawrence-cj** [comment]
What GPU are you using? There maybe misaligned here. Besides, the safe guard `google/shieldgemma-2b` will occupy more GPU memory which is not part of Sana, if you are using app/app_sana.py, refer to: https://github.com/NVlabs/Sana/blob/82ebd2706879b9725d2af903601a64c0e38bfed5/app/app_sana.py#L198.

**Comment by nitinmukesh** [comment]
Thank you @lawrence-cj , Appreciate yours and your team work on releasing this model for us.

I commented the safety checker code and it's fixed.

**Comment by FurkanGozukara** [comment]
@lawrence-cj can we remove safety checker to reduce vram

so this model uses least vram?

ShieldGemma-2B ? 

which model you recommend for least VRAM?
