### ISSUE TITLE
Please use MIT or a commercially available open source license.

### ISSUE THREAD

**Issue by win10ogod** [NVlabs/Sana#21]
Please use MIT or a commercially available open source license.

**Comment by lawrence-cj** [comment]
negotiating

**Comment by lawrence-cj** [comment]
refer to all the headers: https://github.com/NVlabs/Sana/blob/82ebd2706879b9725d2af903601a64c0e38bfed5/app/app_sana.py#L8

**Comment by lawrence-cj** [comment]
The license of Sana's code base is changed to Apacha 2.0
