### ISSUE TITLE
Question about GPU Usage Time and Dataset Size for Training

### ISSUE THREAD

**Issue by YBYBZhang** [NVlabs/Sana#22]
Hello,

Thank you for your amazing work! I have a quick question:

How long does it typically take to train the model on GPUs?
What is the size of the dataset used for training (e.g., number of samples or total size)?
Thank you in advance for your help!

**Comment by lawrence-cj** [comment]
Refer to [PixArt-alpha](https://arxiv.org/abs/2310.00426) and [PixArt-Sigma](https://arxiv.org/abs/2403.04692) for the training cost. We use less training resource than them.

**Comment by YBYBZhang** [comment]
Thanks for your timely reply~
