### ISSUE TITLE
Safetensors? 

### ISSUE THREAD

**Issue by Xenodermus** [NVlabs/Sana#28]
Incredible work guys! Thanks for sharing this with the community. 
Any chance we might see a .safetensors version for either the 512 or 1024 versions? It would be super useful for integrating with platforms like Stable Diffusion, ComfyUI, Forge, and others. What are your thoughts?

**Comment by lawrence-cj** [comment]
https://github.com/huggingface/diffusers/pull/9982

**Comment by lawrence-cj** [comment]
Merged info diffusers and all the diffusers safetensors are release. Closed this issue.
https://huggingface.co/collections/Efficient-Large-Model/sana-673efba2a57ed99843f11f9e
