### ISSUE TITLE
when i try to finetune it it says meta_data.json is missing how do i genrate this file or what is it supost to look like

### ISSUE THREAD

**Issue by Manni1000** [NVlabs/Sana#29]
when i try to finetune it it says meta_data.json is missing how do i genrate this file or what is it supost to look like

**Comment by lawrence-cj** [comment]
update your code to the latest commit.

**Comment by Manni1000** [comment]
Did the training scripts get updated? i see no chage in the file

**Comment by Manni1000** [comment]
maby the standart setting for training shuld be 1 gpu.

**Comment by lawrence-cj** [comment]
Training on non-square image is only supported for webdataset dataloader:
https://github.com/NVlabs/Sana/blob/fa267d5622565d03ade88be77623068c6cf7099b/diffusion/data/datasets/sana_data_multi_scale.py#L40

Multi-scale dataloader for Image-folder below is not supported for now:
https://github.com/NVlabs/Sana/blob/fa267d5622565d03ade88be77623068c6cf7099b/diffusion/data/datasets/sana_data.py#L37

**Comment by Aunali321** [comment]
Interesting. Is there docs on how i can use SanaWebDataset?

**Comment by ShaochengShen** [comment]
@Manni1000 
I follow the guide to form my data structure,but it still reminds me No such file or directory: 'xxxx/meta_data.json'
Do u solve it?

**Comment by Manni1000** [comment]
I did a bit of research on the web dataset formart and used it in another project. it is qute useful if u have lots of files. But i have not solved it here. Maby i can try to solve it in future but i am working on another project sorry.

**Comment by Manni1000** [comment]
The gude on this github is wrong or incomplete

**Comment by ShaochengShen** [comment]
@Manni1000 
I find the Solution in another issue:
The format of meta_data.json should be :
`{
    "name": "sana-dev",
    "__kind__": "Sana-ImgDataset",
    "img_names": [
        "your_img_name1", "your_img_name2"
    ]
}`

**Comment by lawrence-cj** [comment]
OH sry for that. Updated @ShaochengShen
