### ISSUE TITLE
latest.pth file size is null during and at the end of training

### ISSUE THREAD

**Issue by AfterHAL** [NVlabs/Sana#43]
latest.pth file size is null during the training, and also at the end of training :
(default 512 training session with the single cat image, from "Sana_600M_img512.yaml" file)
![image](https://github.com/user-attachments/assets/cd4d9ec1-4c61-49ea-a216-5e873b6d99d5)

**Comment by lawrence-cj** [comment]
latest.pth is a soft link, pointing to the last checkpoint.
