### ISSUE TITLE
A training example with at least 2 images is needed.

### ISSUE THREAD

**Issue by AfterHAL** [NVlabs/Sana#44]
Hi.
With so little information about the dataset settings for training, we need at least an example with 2 images to understand the different json files.
Thanks.
![image](https://github.com/user-attachments/assets/e8ca2123-97b7-4f60-95dc-c66d50e5689c)

**Comment by lawrence-cj** [comment]
[https://github.com/NVlabs/Sana?tab=readme-ov-file#hardware-requirement-1](https://github.com/NVlabs/Sana?tab=readme-ov-file#hardware-requirement-1)

There is no difference as following:
```bash
asset/example_data
├── AAA.txt
├── AAA.png
├── AAA_InternVL2-26B.json
├── AAA_InternVL2-26B_clip_score.json
├── AAA_InternVL2-prompt_clip_score.json
├── BCC.txt
├── BCC.png
├── BCC_InternVL2-26B.json
├── BCC_InternVL2-26B_clip_score.json
├── BCC_InternVL2-prompt_clip_score.json
├── ......
├── CCC.txt
└── CCC.png
├── CCC_InternVL2-26B.json
├── CCC_InternVL2-26B_clip_score.json
├── CCC_InternVL2-prompt_clip_score.json
```

**Comment by lawrence-cj** [comment]
_InternVL2-26B.json, these files contains the image captions from InternVL if you have. They are not necessary, so if you don't have, it's ok actually. 

`meta_data.json` contains two `00000000` means the image will be repeated twice. The number of training image can be modified in this way.

**Comment by arvnoodle** [comment]
but how to generate the metajson files? i have like 300 images here and keeps giving me same error

**Comment by lawrence-cj** [comment]
You just need to put all your image names in the meta.json file.
```yaml
{
    "name": "sana-dev",
    "__kind__": "Sana-ImgDataset",
    "img_names": [
        "your_img_name1", "your_img_name2"
    ]
}
```

**Comment by arvnoodle** [comment]
OH okay! I thought basically like in kohya where it would generate the meta_data.json lol I was checking the code, thought I was missing something. 

Where can I disable the multi gpu? Keep getting issues there with my runpod A100

**Comment by lawrence-cj** [comment]
> Where can I disable the multi gpu? Keep getting issues there with my runpod A100

depends on how you launch the training.
