### ISSUE TITLE
Clarify model license

### ISSUE THREAD

**Issue by VMinB12** [NVlabs/Sana#54]
[The code has been open sourced with an Apache 2.0 license.](https://github.com/NVlabs/Sana/commit/335d4452126952b90376a6f7ccd0ce0490a16fa9) Could you clarify if this license also applies to the model weights? Currently the huggingface page contains a [Attribution-NonCommercial-ShareAlike 4.0 International license](https://huggingface.co/Efficient-Large-Model/Sana_1600M_1024px/blob/main/LICENSE.txt). Is this correct and up to date?

Please consider also open sourcing the model weights. Thanks for the great work.

**Comment by CorradoF** [comment]
So if I train sana model from scratch I can use it commercially?

**Comment by lawrence-cj** [comment]
As your wish
