### ISSUE TITLE
Actual training example config seem to train from scratch. How to fine-tune from pre-trained state of Sana ?

### ISSUE THREAD

**Issue by AfterHAL** [NVlabs/Sana#55]
Hi.
My question is in the title, and if it's possible to train from a pre-trained Sana model, I wonder how to use the "model" and "load_from" parameters.

```
"model": {
        "model": "SanaMS_600M_P1_D28",
        "load_from": null,
        "resume_from": {
            "checkpoint": "latest",
            "load_ema": false,
            "resume_optimizer": true,
            "resume_lr_scheduler": true
        },
```
Thank you.

**Comment by lawrence-cj** [comment]
Set the model path to load_from

**Comment by AfterHAL** [comment]
> Set the model path to load_from

Hi. Do you mean set "load_form" to the model path ?
Thank you.
