### ISSUE TITLE
[Question]Where can i run this? ComfyUI? SD.next?

### ISSUE THREAD

**Issue by VeteranXT** [NVlabs/Sana#59]
Title says it all?

**Comment by jajabum** [comment]
![image](https://github.com/user-attachments/assets/b768e732-5288-4711-8c67-dda0118c0001)

**Comment by AfterHAL** [comment]
I saw this "ComfyUI-Sana" code the other day, but I didn't try it.
https://github.com/zmwv823/ComfyUI-Sana

**Comment by VeteranXT** [comment]
I guess when it arrives then.

**Comment by jajabum** [comment]
> Я видел этот код "ComfyUI-Sana" на днях, но я не пробовал его. https://github.com/zmwv823/ComfyUI-Sana

I've tried it. It works on Windows 10

**Comment by lawrence-cj** [comment]
ComfyUI is also released.https://github.com/NVlabs/Sana/blob/main/asset/docs/ComfyUI/comfyui.md

**Comment by yujincheng08** [comment]
#80
