### ISSUE TITLE
Inquiry about Training Data Used in the Sana Paper and Its Availability

### ISSUE THREAD

**Issue by taki0112** [NVlabs/Sana#6]
I have thoroughly read the Sana paper and found it highly insightful. 
However, I couldn't find detailed information regarding the training data used for the model. 

Could you please provide clarification on the following points?
* What specific datasets were used to train the Sana model?
* Is there any plan to release or make the training data publicly available for research purposes?

I believe that knowing more about the data used in training would greatly benefit the research community.
Thank you for your time and for sharing your work.

**Comment by lawrence-cj** [comment]
Data is a senstive thing. We will discuss about it later.

**Comment by lawrence-cj** [comment]
Refer to: https://github.com/NVlabs/Sana/issues/95
