### ISSUE TITLE
lora train?

### ISSUE THREAD

**Issue by Deng-Xian-Sheng** [NVlabs/Sana#61]

**Comment by Deng-Xian-Sheng** [comment]
I'm afraid I can't adapt to the task of lora train yet.
﻿
However, I feel that the performance of full training is poor. I don't mean that the performance is poor because it is "full", but I feel that there is a lack of optimization to reduce the memory usage.

**Comment by Deng-Xian-Sheng** [comment]
Are there any guidelines for training?

**Comment by TotallyTroll** [comment]
What is the difference between this trainings methods?
1) https://github.com/NVlabs/Sana?tab=readme-ov-file#-3-how-to-train-sana
2) https://github.com/NVlabs/Sana/blob/main/asset/docs/sana_lora_dreambooth.md

In the first one I can see the proper dataset used, with images and tags to each one. Still there is no word about lora. So what will be trained at the end?

As to the second one - example is quite useless. 5 pictures with dogs, and no word how to align it with tags/prompts.

P.S. Any proper lora training workflow for ComfyUI?
