### ISSUE TITLE
validation_prompts are sampling twice ?

### ISSUE THREAD

**Issue by AfterHAL** [NVlabs/Sana#63]
Hi there.
I wonder why there are 10 images in the sampling done with the validation_prompt prompts during the training (at X steps), when I only set 5 prompts for x step sampling.

![vis_28750_w_init](https://github.com/user-attachments/assets/d1f58990-261c-4191-9caf-98b527e04251)

It seems that the top pictures are (slowly) getting the concepts and following the prompts: for example, the first validation prompt is "a black and white photograph of..." and the second is "a red shirt.". (and the inference tests I do on the fully trained from scratch shows that it goes the right direction.)

But what are the five images in the second row ? The second one seem to follow the sampling prompt "a red shirt", but I don't understand the similarities of images 6,8,9 and 10 (bottom line).

Regards.

**Comment by lawrence-cj** [comment]
> That's because 5 images are generated with a fixed seed, and the other 5 with random seed

Exactly correct answer.

**Comment by AfterHAL** [comment]
Thank you @Muinez & @lawrence-cj .
