### ISSUE TITLE
dc-ae and text-encoder load

### ISSUE THREAD

**Issue by wanglaofei** [NVlabs/Sana#67]
How to config the local DC-AE and Text-Encoder path? I have downloaded the related models in my local computer, but I don't know how to load the local DC-AE and Text-Encoder. Thanks for any help!

**Comment by moeinheidari7829** [comment]
> How to config the local DC-AE and Text-Encoder path? I have downloaded the related models in my local computer, but I don't know how to load the local DC-AE and Text-Encoder. Thanks for any help!

Hi. I hope you are doing well. Can you please tell me how you manually downloaded the checkpoints to your local?

**Comment by lawrence-cj** [comment]
For vae and text encoder loading:

https://github.com/NVlabs/Sana/blob/a8f3488942101d629a3e16ec3d234cfd1515414f/diffusion/model/builder.py#L80

https://github.com/NVlabs/Sana/blob/a8f3488942101d629a3e16ec3d234cfd1515414f/diffusion/model/builder.py#L44
