### ISSUE TITLE
In the demo, setting the CFG guidance scale value to 1 results in a runtime error.

### ISSUE THREAD

**Issue by haruharu-1105** [NVlabs/Sana#7]
URL:
https://8876bd28ee2da4b909.gradio.live/
Prompt:
`A modern, gray wooden dresser with a double mirror set and an attractive vase of greenery sits on the floor, complementing the neutral-toned decor in the room.`

Advanced options:
![image](https://github.com/user-attachments/assets/c13d827a-5b86-4793-bc81-b00c6b72f317)

**Comment by ashrafbay** [comment]
This didn't happen to me even though I tried it
You may have a connection problem

**Comment by lawrence-cj** [comment]
Bug has been fixed. Thanks a lot for noticing! try our new demo site: https://sana-gen.mit.edu/

**Comment by haruharu-1105** [comment]
I have confirmed the fix. Thank you for taking the time out of your busy schedule to correct it. I'm closing the issue because it's resolved.
![image](https://github.com/user-attachments/assets/a3b5509a-17d3-4190-8ebb-b86116a42054)
