### ISSUE TITLE
What's the difference between dc-ae-sana and dc-ae-mix?

### ISSUE THREAD

**Issue by noanti** [NVlabs/Sana#75]
1. I tried`mit-han-lab/dc-ae-f32c32-sana-1.0-diffusers`  and `mit-han-lab/dc-ae-f32c32-mix-1.0-diffusers`, and found the reconstruction of `mix` is better. What's the difference?

2. I tested `f32` `f64` `f128` mix model, I think f64 is the best, but they all didn't achieve the effect in the model card gif.
![image](https://github.com/user-attachments/assets/89b992b9-a932-49da-afda-db7e9c8bb1ff)
origin image:
![image](https://github.com/user-attachments/assets/90f7045c-e439-4fe0-8595-56000e1557ea)
f64 reconstruction:
![image](https://github.com/user-attachments/assets/817876a0-3632-444e-bf0e-7767a1337fef)
f32 reconstruction:
![image](https://github.com/user-attachments/assets/c6628fee-35f4-4a3c-bbed-5467c405d589)

Will there be a new Sana model based on f64-dc-ae?

**Comment by lawrence-cj** [comment]
1. The mix version trained with more data and longer time. We will choose a newer version of DC-AE in our next Sana release.
2. DC-AE will work better at resolution up to 1024px. We are also working on the DC-AE-1.5 for better construction ability.

**Comment by noanti** [comment]
Cool! When will the next Sana model be released?

**Comment by lawrence-cj** [comment]
It will take months.
