### ISSUE TITLE
ComfyUI nodes are available for Sana and DC-AE

### ISSUE THREAD

**Issue by lawrence-cj** [NVlabs/Sana#80]
https://github.com/NVlabs/Sana/blob/main/asset/docs/ComfyUI/comfyui.md

**Comment by Bocchi-Chan2023** [comment]
Hi, is it possible to support diffusers checkpoint type of sana?
since OneTrainer only supports diffusers checkpoints output

**Comment by RandomGuyWithIssues** [comment]
Please make this available in comfyui manager or comfy registry as a proper custom node.

**Comment by Clusters** [comment]
are the new Sana 1.5 models compatible with ComfyUI?

**Comment by frutiemax92** [comment]
Any update planned for diffusers format checkpoints?
