### ISSUE TITLE
1024px vs 2048px image is same? 

### ISSUE THREAD

**Issue by FurkanGozukara** [NVlabs/Sana#83]
Here I will demonstrate what I mean

First image

![image](https://github.com/user-attachments/assets/45c2cf0d-2abd-44db-b1b0-1165afbe4817)

Used configs

![image](https://github.com/user-attachments/assets/a526b765-f5c5-43b2-8657-a74baee1fd31)

Second image

![image](https://github.com/user-attachments/assets/eace98a2-cccb-445b-8ca0-3b0bfea48cec)

Used configs

![image](https://github.com/user-attachments/assets/58b8fd49-623f-4517-9e24-87b8ccb58712)

And here 3 rd image which I used Lanczos

![image](https://github.com/user-attachments/assets/7fa094b2-01cb-47a0-a6f3-6fe2911e8ecd)

![image](https://github.com/user-attachments/assets/9627386d-055b-4986-b57e-b38af23ded0d)

As you can see the model generates same image and just upscale with something which is even worse than upscale of paint .net Lanczos

**Comment by Kallamamran** [comment]
I think so as well. I have tried the model as well and no matter what resolution you chose it generates the same image. Generate it lower resolution it takes X time and the image is downscaled. Generate it in 4K and it takes the same time, but the image seems upscaled.... I don't know, but something seams fishy!

**Comment by ShaochengShen** [comment]
According to the code, the inference code only support 1024px images generation. If use the different resolution rather than settings in the default config, it seems like just using the Lanczos upsample.
![image](https://github.com/user-attachments/assets/136aea49-e6b5-4290-893f-d530ff60f973)

**Comment by FurkanGozukara** [comment]
@ShaochengShen this explains a lot
so it is hard coded 

can  we change it do you think?

**Comment by ShaochengShen** [comment]
@FurkanGozukara 
I just emailed the author, and according to the response, the "bilinear interpolation" is primarily used to constrain resolutions. However, the quality of the generated image cannot be guaranteed if we use a 1024px checkpoint to generate higher-resolution images. Therefore, to produce higher-resolution pictures (e.g., 2048px or 4096px), we need to wait for the release of 2k or 4k checkpoints.

Btw, we can use other methods to improve the gen quality.

**Comment by FurkanGozukara** [comment]
@ShaochengShen thanks. so they gonna publish higher resolution checkpoints?

**Comment by Kallamamran** [comment]
I tried it yesterday and the model downloading is a 1024x-named model. Should be saying alot. As you said... We need to wait for 2048x and/or 4096x models to be realeased. Question is how well the bragging about speed and VRAM-usage works with those models 🤔

**Comment by xieenze** [comment]
We will release 2K and 4K checkpoints very soon. Thank you for your patience!

**Comment by ShaochengShen** [comment]
@Kallamamran 
Actually, you can try to gen 2K or 4K pics now by yourself. The speed and VRAM-usage can be test without ckpts. With my experiment, 2K pics can be generated in 5s on Nvidia RTX 4090, 4K pics need more than 20s and more consumption of GPU resource.
Btw, I recommend a plug-in method which can generate pics faster and keep the gen quality. Maybe can improve sana. https://github.com/haoningwu3639/MegaFusion
