### ISSUE TITLE
Request for training to use jpg and jpeg dataset source format (in addition to png).

### ISSUE THREAD

**Issue by AfterHAL** [NVlabs/Sana#84]
Hi.
I would change it myself if I could, but I have no clue where to do it in the code.
Thanks.

**Comment by lawrence-cj** [comment]
You may change the related code here:
https://github.com/NVlabs/Sana/blob/41dcbe92671682216d357c385c0d3d7dab0e8e55/diffusion/data/datasets/sana_data.py#L52

**Comment by AfterHAL** [comment]
> You may change the related code here:
> 
> https://github.com/NVlabs/Sana/blob/41dcbe92671682216d357c385c0d3d7dab0e8e55/diffusion/data/datasets/sana_data.py#L52

Hey @lawrence-cj , you do a great job, but please, don't answer things like "just do it". It's not funny at all.
So, I do understand that I must change the input extension format because that's what I wanna do, but how to use jpg "in addition to png" ?
How do I change this line of code to achieve this simple goal before I die ?

**Comment by geronimi73** [comment]
> but please, don't answer things like "just do it"

He didn't. He told you exactly what to do.

**Comment by AfterHAL** [comment]
> > but please, don't answer things like "just do it"
> 
> He didn't. He told you exactly what to do.

Ok. So "img_extension=".png & .jpg & jpeg (please)",  would be ok, but it's not.

**Comment by lawrence-cj** [comment]
So, you mean you want to blend png jpg and jpeg all together to train?

**Comment by AfterHAL** [comment]
> So, you mean you want to blend png jpg and jpeg all together to train?

Hi @lawrence-cj .
Yes, I would like to be able to mix jpg and png sources.

**Comment by lawrence-cj** [comment]
OK. I'll try to figure out a solution and let u know.

**Comment by lawrence-cj** [comment]
Try to fix here: https://github.com/NVlabs/Sana/pull/94
@AfterHAL

**Comment by AfterHAL** [comment]
> Try to fix here: #94 @AfterHAL

Thank you @lawrence-cj .

**Comment by lawrence-cj** [comment]
@AfterHAL The fix is passed and merged. 
https://github.com/NVlabs/Sana/pull/94

The new meta_data.json is like:
https://github.com/NVlabs/Sana/blob/2799bdc13dce1c147ab99926f96ab74fab4394e7/asset/example_data/meta_data.json#L1-L6
You can specify the specific image name into the `img_names` list.

**Comment by AfterHAL** [comment]
Hi @lawrence-cj .
It works fine. Thanks a lot.
