### ISSUE TITLE
OSError: You are trying to access a gated repo.

### ISSUE THREAD

**Issue by shaun-ba** [NVlabs/Sana#85]
Neither the main Gradio repo nor Comfy will work whilst you have reliance on gated repo/model.

**Comment by lawrence-cj** [comment]
Then, I will change to a non-gated repo.

**Comment by shaun-ba** [comment]
Super excited to test this out locally and even more excited for the 4096 checkpoints, keep it up!

**Comment by lawrence-cj** [comment]
We updated the code, could you give it a try?

```bash
cd ./ComfyUI/custom_nodes/ComfyUI_ExtraModels
git pull
```

**Comment by shaun-ba** [comment]
@lawrence-cj I was getting that error on your own Gradio repo, but it would also translate to Comfy.

On Comfy your workflow will not work as it has nothing there to download models. If you just update the readme with links to the models required that should suffice? I'm not aware of a model auto downloader in comfy so you are referencing files that don't and will never exist?

```
Prompt outputs failed validation
SanaCheckpointLoader:
- Value not in list: ckpt_name: 'ex\Sana_1600M_1024px.pth' not in (list of length 31)
ExtraVAELoader:
- Value not in list: vae_name: 'xp\dc_ae_f32c32_sana_1.0_diffusers.safetensors' not in ['mit-han-lab/dc-ae-f32c32-sana-1.0-diffusers', 'ae.safetensors']
- Value not in list: vae_type: 'dcae-f32c32-sana-1.0' not in ['kl-f4', 'kl-f8', 'kl-f8-d16', 'kl-f16', 'kl-f32', 'vq-f4', 'vq-f8', 'vq-f16', 'Consistency-Decoder', 'SDV-VideoDecoder', 'MoVQ3', 'dcae-f32c32-sana-1.0-diffusers']
```

**Comment by shaun-ba** [comment]
> > cannot import name 'cached_download' from 'huggingface_hub' (/miniconda3/envs/comfy/lib/python3.12/site-packages/huggingface_hub/**init**.py)
> 
> Then I think you need to upgrade the `huggingface_hub`?

I updated but still the same error

```
Installing collected packages: huggingface_hub
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface-hub 0.26.2
    Uninstalling huggingface-hub-0.26.2:
      Successfully uninstalled huggingface-hub-0.26.2
Successfully installed huggingface_hub-0.26.5
```

**Comment by shaun-ba** [comment]
@lawrence-cj  I downgraded to 0.25.0 which fixed that first import issue, but now I have another:

```
cannot import name 'FromOriginalModelMixin' from 'diffusers' 
```

seems like more testing needed, as now I'm messing around with global comfy packages and i've never had a single issue running comfy!

**Comment by lawrence-cj** [comment]
Seems like you need to use a correct diffusers. What about 
`pip install -U diffusers`
We use Gemma and some newest models, which may need a newer version of diffusers, transformers and so on.
I tested in our env setting here which is available. https://github.com/NVlabs/Sana#-1-dependencies-and-installation

**Comment by shaun-ba** [comment]
> Seems like you need to use a correct diffusers. What about `pip install -U diffusers` We use Gemma and some newest models, which may need a newer version of diffusers, transformers and so on. I tested in our env setting here which is available. https://github.com/NVlabs/Sana#-1-dependencies-and-installation

No, I also tried lowering the version and the latest version of this as per a google link in the hope that would fix it. It doesn't.

Your own code/repo doesn't even work, regardless of ComfyUI.

You reference an "environment" in your link, but I don't see anything apart from "environment_setup.sh" which doesn't include any diffusers install version, there is no pip requirements file or anything here.

**Comment by lawrence-cj** [comment]
> You reference an "environment" in your link, but I don't see anything apart from "environment_setup.sh" which doesn't include any diffusers install version, there is no pip requirements file or anything here.

About this, you need to know. `pip install -e .` here: https://github.com/NVlabs/Sana/blob/bcad148693affa4f6a971516b57e75d2ee0b3221/environment_setup.sh#L27

It will include the [pyproject.toml](https://github.com/NVlabs/Sana/blob/main/pyproject.toml) to prepare all the env we need. Refer to https://github.com/NVlabs/Sana/blob/bcad148693affa4f6a971516b57e75d2ee0b3221/pyproject.toml#L1

**Comment by lawrence-cj** [comment]
> Could you push the huggingface cached changed to your own standalone app repo as well?

We will update it after everything is ready soon.
