### ISSUE TITLE
module 'xformers.ops.fmha' has no attribute 'BlockDiagonalMask'

### ISSUE THREAD

**Issue by Alfaman1969** [NVlabs/Sana#87]
module 'xformers.ops.fmha' has no attribute 'BlockDiagonalMask'  ?????????

**Comment by zrealli** [comment]
> xformers

Please make sure your xformers's version is right.

**Comment by lawrence-cj** [comment]
We rely on `"xformers==0.0.27.post2`

**Comment by se7enth** [comment]
same problem .  Are there any plans to support the new version ex. 0.0.28.post1?

**Comment by lawrence-cj** [comment]
We rely on xformers==0.0.27.post2. There is no plan for more version supporting for now, since xformers is not a necessary lib in our repo. We can replace it with Flash attention in F.scaled_dot_pro()
