### ISSUE TITLE
cannot import name 'SanaPipeline' from 'diffusers' 

### ISSUE THREAD

**Issue by yuvraj108c** [NVlabs/Sana#90]
Installed from source using `pip install git+https://github.com/huggingface/diffusers`
Version: 0.32.0.dev0

**Comment by yujincheng08** [comment]
waiting for huggingface/diffusers#9982

**Comment by yuvraj108c** [comment]
Yes your branch works!

**Comment by lawrence-cj** [comment]
`diffusers` merged Sana. Just need to run `pip install -U diffusers` and it will work.
