### ISSUE TITLE
How much training data was used to train Sana?

### ISSUE THREAD

**Issue by omrastogi** [NVlabs/Sana#95]
First, let me extend my congratulations on your exceptional work—your results are both elegant and impactful.

I am considering training Sana for a different task. However, to effectively evaluate its performance, I need to know the exact number of image samples the model was trained on.

While your paper provides a comprehensive description of the dataset processing pipeline, I was unable to locate the precise number of training samples employed.

I would greatly appreciate your time and assistance in providing this information.

**Comment by lawrence-cj** [comment]
About the data volume, you can refer to PixArt-alpha and PixArt-Sigma, which is around 30M image-data pairs.

**Comment by micklexqg** [comment]
> About the data volume, you can refer to PixArt-alpha and PixArt-Sigma, which is around 30M image-data pairs.

however, still not find specific information about training data,  so, what is the dataset name and how to get it?
